### ISSUE TITLE
Update Behavior Tree Diagram

### ISSUE THREAD

**Issue by ZefraSK** [Weber-State-Submarine-Project/Submarine#32]
DONE: When diagram represents actual code

**Comment by ZefraSK** [comment]
[BehaviorTree.pdf](https://github.com/user-attachments/files/15844485/BehaviorTree.pdf)

**Comment by Ben1219925** [comment]
Updated with slightly better dimensions for readability, removed battery check


[Behavior Tree.pdf](https://github.com/user-attachments/files/16033149/Behavior.Tree.pdf)
