### ISSUE TITLE
Test Sonar with simulation

### ISSUE THREAD

**Issue by ZefraSK** [Weber-State-Submarine-Project/Submarine#41]
DONE: When tested sonar with the simulation

**Comment by Ben1219925** [comment]
After adding the Python node that interprets the sonar UART data I published this to scan/down and used it as the downward facing sonar, the floor formed at the level of the real world sonar without any issues.

This was done on a small scale environment at 0 0.16 m but it should scale up to pool size in the same way.
Sonars should be pretty easy to incorporate into the software from the real sub as the python script is complete and will be nearly identical for all 3 sonars.

**Comment by ZefraSK** [comment]
Ros2 Node Created - Ben 

It indeed makes a map
