### ISSUE TITLE
Get Simulation to work with Jazzy

### ISSUE THREAD

**Issue by ZefraSK** [Weber-State-Submarine-Project/Submarine#53]
DONE: When we know if simulation works with jazzy

**Comment by Ben1219925** [comment]
Jazzy uses URDF models instead of SDF models in order to bridge from gz-sim to ros2, I now have the model showing in gz-sim but I'm still having trouble getting it to work on the ros2 side with rviz, also the sensor packages are different and don't currently work.

Will continue working on it.

**Comment by Ben1219925** [comment]
Github Jazzy branch has been updated and is fully functional
