### ISSUE TITLE
Rewrite speed sensor code and test accuracy

### ISSUE THREAD

**Issue by Ben1219925** [Weber-State-Submarine-Project/Submarine#83]
Done: Rewrite the provided Arduino code to fix minor issues.
Test the accuracy of the sensor.

**Comment by ZefraSK** [comment]
No longer has a weird issue of detecting a 1 instead of a 0. We do not know how to test it yet. It feels a little laggy

**Comment by ZefraSK** [comment]
Date: 10/21/24
Current Status:

The Garmin Speed Sensor is not usable. We are not moving nearly fast enough to get the wheel to spin.

Currently I have coding a ping_velocity that calculates velocity using the distance from the ping.

According to a ME, a Pitot Tube will surely suffice to our issue. Pitot Tube simply calculates the velocity based on the pressure of the inside vs outside. I found this one that could our need ([Water Flow Sensor](https://www.pasco.com/products/sensors/pasport/general-flow-sensor)) which will cost around ~$265. This either communicates analog or digital. More research must be done on how it communicates.

| **Parameter**           | **Specification**                          |
|-------------------------|--------------------------------------------|
| **Pressure Range**       | 0 to 50 kPa                                |
| **Pressure Accuracy**    | ±2.5% of Full Scale (0 to 85ºC)            |
| **Resolution**           | 0.2% of Full Scale                        |
| **Venturi Range**        | 0 to 84 gpm (water); 0 to 773 gpm (air)    |
| **Venturi Accuracy**     | ±2 gpm (water); ±2.5 cf/min (air)          |
| **Pitot Range**          | 0 to 9.98 m/s (water); 0 to 92.1 m/s (air) |


I'm thinking for robot_localization we use the following:
- Ping_velocity Velocity Calculator
- BNO085 Linear Acceleration (If we can calibrate)
- Pitot Tube if needed and in budget

**Comment by ZefraSK** [comment]
Date: 10/28/24
Current Status:
Ben coded up a xyz position node rather than a velocity node using the ping. We are shoving these values into the EKF for robot_localization. It is somewhat working. 

Currently we need to see if we need a LPF for the sonars
